### ISSUE TITLE
Why Scale Spellbook instead of raw OpenAI endpoint?

### ISSUE THREAD

**Issue by aavetis** [TheAppleTucker/backend-GPT#5]
https://github.com/TheAppleTucker/backend-GPT/blob/main/backend/server.py#L11

What is the spellbook doing, and also if it's just hitting OpenAI, why not just use their endpoints? Thanks!

**Comment by evanmays** [comment]
1. This was a Scale hackathon project so we got credits for their Spellbook product which is a prompt engineering tool.
2. I tried OpenAI since it's easier to use than Spellbook, but they scan public got repos for API keys. They kept canceling my keys so I had to keep rotating keys

Tldr; non technical reasons. And feel free to use my scale key until the credits run out
